### ISSUE TITLE
Check duplicity of OpenSSL documentation

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/usable-cert-validation#13]
If it's really duplicity, submit a merge request to update the one with less info.

**Comment by zacikpa** [comment]
I've made a list of differences between the error code documentation of _openssl verify_ and _X509_STORE_CTX_get_error_:

- Written in _verify_ manpage:
"Previous versions of this documentation swapped the meaning of the X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT and X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY error codes."
This is fixed in the newest _verify_ manpage.
However, the _X509_STORE_CTX_get_error_ manpage doesn't have the meanings swapped yet.

- _X509_STORE_CTX_get_error_ manpage is missing quite a lot of error codes compared to _verify_ manpage.
Some of them are:
X509_V_ERR_UNSPECIFIED
X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER
X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION
X509_V_ERR_KEYUSAGE_NO_CRL_SIGN
...
And many more. Whether these cannot be returned with the _X509_STORE_CTX_get_error_ 
function, or they are just missing from the documentation, I don't know. 

- Four errors are marked as unused in the _verify_ manpage starting with X509_V_ERR_SUBJECT_ISSUER_MISMATCH.
In the _X509_STORE_CTX_get_error_ manpage, these still have detailed descriptions present.

- For some errors, the _X509_STORE_CTX_get_error_ manpage has a more detailed description. These are:
X509_V_ERR_INVALID_EXTENSION
X509_V_ERR_INVALID_POLICY_EXTENSION
X509_V_ERR_NO_EXPLICIT_POLICY
X509_V_ERR_DIFFERENT_CRL_SCOPE
X509_V_ERR_UNSUPPORTED_EXTENSION_FEATURE
X509_V_ERR_PERMITTED_VIOLATION
X509_V_ERR_EXCLUDED_VIOLATION
X509_V_ERR_SUBTREE_MINMAX
X509_V_ERR_UNSUPPORTED_CONSTRAINT_TYPE
X509_V_ERR_UNSUPPORTED_CONSTRAINT_SYNTAX
X509_V_ERR_CRL_PATH_VALIDATION_ERROR
X509_V_ERR_APPLICATION_VERIFICATION

**Comment by mukrop** [comment]
Thanks, great overview!

> Whether these cannot be returned with the X509_STORE_CTX_get_error
function, or they are just missing from the documentation, I don't know.

This is what we should check now. Based on the result, I suggest making a pull request unifying the documentation.

**Comment by mukrop** [comment]
* Pull request for reversed meaning done.
* Awaiting: Pull request for "For some errors, the X509_STORE_CTX_get_error manpage has a more detailed description."
* For the other two bullets, further investigation is necessary.
* Nit-pick: Unify order of errors and initial capital letters in documentation.

**Comment by mukrop** [comment]
> Four errors are marked as unused in the verify manpage starting with X509_V_ERR_SUBJECT_ISSUER_MISMATCH.
In the X509_STORE_CTX_get_error manpage, these still have detailed descriptions present.

Leave this as is -- the errors could be thrown by CLI but cannot any longer, their short mention makes sense (and it illustrates we want to have there only errors that can realistically be thrown).

**Comment by zacikpa** [comment]
>X509_STORE_CTX_get_error manpage is missing quite a lot of error codes compared to verify manpage.

Here is the list of all of them: 
X509_V_ERR_UNSPECIFIED				
X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER
X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION
X509_V_ERR_KEYUSAGE_NO_CRL_SIGN
X509_V_ERR_UNHANDLED_CRITICAL_CRL_EXTENSION
X509_V_ERR_INVALID_NON_CA
X509_V_ERR_PROXY_PATH_LENGTH_EXCEEDED
X509_V_ERR_PROXY_SUBJECT_INVALID
X509_V_ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE
X509_V_ERR_PROXY_CERTIFICATES_NOT_ALLOWED
X509_V_ERR_UNNESTED_RESOURCE
X509_V_ERR_PATH_LOOP				
X509_V_ERR_SUITE_B_INVALID_VERSION
X509_V_ERR_SUITE_B_INVALID_ALGORITHM
X509_V_ERR_SUITE_B_INVALID_CURVE
X509_V_ERR_SUITE_B_INVALID_SIGNATURE_ALGORITHM
X509_V_ERR_SUITE_B_LOS_NOT_ALLOWED
X509_V_ERR_SUITE_B_CANNOT_SIGN_P_384_WITH_P_256
X509_V_ERR_HOSTNAME_MISMATCH
X509_V_ERR_EMAIL_MISMATCH
X509_V_ERR_IP_ADDRESS_MISMATCH
X509_V_ERR_DANE_NO_MATCH
X509_V_ERR_EE_KEY_TOO_SMALL
X509_ERR_CA_KEY_TOO_SMALL
X509_ERR_CA_MD_TOO_WEAK
X509_V_ERR_INVALID_CALL
X509_V_ERR_STORE_LOOKUP
X509_V_ERR_NO_VALID_SCTS
X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION
X509_V_ERR_OCSP_VERIFY_NEEDED
X509_V_ERR_OCSP_VERIFY_FAILED
X509_V_ERR_OCSP_CERT_UNKNOWN

**Comment by zacikpa** [comment]
In the OpenSSL master version, all documentation is now migrated to the X509_STORE_CTX_get_error manpage. The only missing errors are the suite_b errors (#70), this issue can be closed.
